### ISSUE TITLE
IPFBrowser crashes attempting to viewing some custom IPFs

### ISSUE THREAD

**Issue by celophi** [exectails/IPFBrowser#2]
I haven't looked at the code yet, but I realized that addons are also read by IPFBrowser when attempting to extract an entire directory. In some cases such as the developer console, this will cause the tool to crash. I'm not sure exactly why the crash occurs, but a warning message or a notification might be appropriate when the tool is unable to extract/view the file.

**Comment by exectails** [comment]
Custom IPFs, huh? Gotta look into that. I imagine they might be malformed in some way that doesn't bother the client. You're right that it should at least give some message.

**Comment by exectails** [comment]
Found the problem, the files in the developer console IPF aren't being decrypted, which causes the decompression to throw an exception, because the data is invalid. I'm checking the IPF version to decide whether to decrypt or not, because prior to i11000, the IPFs weren't encrypted, and I wanted IPFBrowser to be able to handle everything. The dev console addon uses version 0 though.

Since I doubt that there's an official version 0 IPF, I'm gonna add that to the condition.
```csharp
if (this.Ipf.Footer.NewVersion > 11000 || this.Ipf.Footer.NewVersion == 0)
```
With this, I was able to extract this IPF just fine.
